server:
  port: 80
spring:
  application:
    name: mscloud-consumer-order
eureka:
  client:
    #把自己注册进eureka注册中心
    register-with-eureka: true
    #是否从eurekaServer抓取已有的信息，默认true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: mscloud-consumer-order80
    prefer-ip-address: true